DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS refresh_token;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE refresh_token (
    rt_key VARCHAR(255) NOT NULL,
    rt_value VARCHAR(255),
    PRIMARY KEY (rt_key)
);
